create table Groups(
    group_id   int         not null, constraint pk_groups_group_id primary key(group_id), 
    group_name varchar(64) not null, constraint u_groups_group_name unique(group_name)
);

create table Students(
    student_id int         not null generated by default as identity, constraint pk_students_student_id primary key(student_id),
    name       varchar(64) not null,
    group_id   int         not null, constraint fk_students_group_id foreign key(group_id) references Groups(group_id)
);

create table Courses(
    course_id   int         not null generated by default as identity, constraint pk_courses_courses_id primary key(course_id),
    course_name varchar(64) not null
);

create table Lectures(
    lecturer_id   int         not null generated by default as identity, constraint pk_lectures_lecturer_id primary key(lecturer_id),
    lecturer_name varchar(64) not null
);

create table Marks(
    mark        decimal(6, 3) not null,
    student_id  int           not null, 
        constraint fk_marks_student_id foreign key(student_id) references Students(student_id),
    course_id   int           not null, 
        constraint pk_marks primary key(student_id, course_id), 
        constraint fk_marks_course_id foreign key(course_id) references Courses(course_id),
    lecturer_id int           not null, constraint fk_marks_lecturer_id foreign key(lecturer_id) references Lectures(lecturer_id)
);
