#!/bin/bash
while true;
do
read line
case "$line" in
    TERM)
        kill -SIGTERM $(cat operations07)
        exit
        ;;
    +)
        kill -USR1 $(cat operations07)
        ;;
    [*])
        kill -USR2 $(cat operations07)
        ;;
	*)
	    continue
	;;		
esac
done
