name:                hw03
version:             0.1.0.0
github:              "githubuser/hw03"
license:             BSD3
author:              "Vladislav Kuznetsov"
maintainer:          "vladrus13rus@yandex.ru"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hw03#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- optparse-applicative
- time
- filepath
- strict
- transformers
- split

library:
  source-dirs: src

executables:
  hw03-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hw03

tests:
  hw03-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hw03
