[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.tpl.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.tpl.model.User" --]
[#-- @ftlvariable name="uri" type="java.lang.String" --]
[#-- @ftlvariable name="links" type="ru.itmo.tpl.model.Link[]" --]
[#-- @ftlvariable name="link" type="ru.itmo.tpl.model.Link" --]
[#-- @ftlvariable name="posts" type="ru.itmo.tpl.model.Post[]" --]
[#-- @ftlvariable name="post" type="ru.itmo.tpl.model.Post" --]